name: portafolio_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  change_app_package_name: ^1.5.0
  cloud_firestore: ^6.0.0
  dio: ^5.9.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.5.4
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.0
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.10.0
  formz: ^0.8.0
  go_router: ^6.2.0
  google_maps_flutter: ^2.12.3
  lorem_ipsum: ^0.0.3
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.13
  intl: ^0.20.2
  image_picker: ^1.2.0
  marquee: ^2.3.0
  mailto: ^2.0.0
  url_launcher: ^6.3.2
  mailer: ^6.5.0
  animate_do: ^4.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#252829"
  image: "assets/icons/AR_2.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/AR_2.png"


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/avatar.png
    - assets/icons/AR_2.png
    - assets/icons/Camera_Icon.svg
    - assets/icons/topBar/
    - assets/images/
    - assets/logo/
    - assets/loaders/
    - assets/images/brillos/
    # - assets/images/
    # - assets/fonts/

